# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78e5c70bf6e7345e831320de301327dd5a8cfdd159730ca57bd0a6fedcba38b1d8f80beabaf2413a8bcc2392d8aeb9151b3ff9932d0d344b25ab799f234e16df

test:
  secret_key_base: 19ffe773956706ecfecef22eb6478eb88cb5a304d2df434bff693a15ffc63fc95e44b79f94760a681ed37f354e308453f02efdf2b396a29bca835483b62360a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
